// ── FreeTTS watermark trimmer ───────────────────────────────────────────────
// freetts.org appends a spoken "Generated by FreeTTS" tag to EVERY synthesis —
// its JSON even admits it (`"watermark":"end"`), and no request parameter turns
// it off (verified live: watermark:false / "none" / "off" / removeWatermark are
// all silently ignored). ffmpeg silence analysis of files from both app voices
// shows a deterministic tail structure:
//   [real speech][~1.6s silence gap][~1.77s watermark speech][~0.82s trailing silence]
// so the whole watermark block occupies the last ~4.19s of every file. Cutting
// anywhere in [D−4.19s, D−2.59s] removes it; we cut at D−3.4s (mid-gap, ~0.8s
// of slack on both sides against vendor-side drift).
//
// Implemented as a pure-JS MP3 frame splice — this runs inside the Vercel
// serverless function (api/index.mjs), where native binaries like ffmpeg don't
// exist. MP3 frames are independently decodable, so dropping whole frames from
// the END is lossless for the frames kept (the bit reservoir only points
// backwards). Any parse surprise ⇒ null ⇒ the route serves the original audio
// untouched (fail-open: a watermark is better than no audio at all).

// Seconds cut from the end — must land inside the post-speech silence gap
// (gap ≈ 1.6s + watermark ≈ 1.77s + trailing ≈ 0.82s ⇒ safe window ≈ 2.6–4.2s).
const WATERMARK_CUT_SECONDS = 3.4;
// Never keep less real speech than this: a shorter file either has no room for
// the full watermark block or would have its actual content eaten by the cut.
const MIN_KEEP_SECONDS = 2.0;
const MIN_TOTAL_SECONDS = 5.0;

// Layer III bitrate tables, kbps indexed by the 4-bit header field.
const BITRATES_V1_L3 = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0];
const BITRATES_V2_L3 = [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160, 0];
// Sample rates by MPEG version bits (3 = MPEG1, 2 = MPEG2, 0 = MPEG2.5).
const SAMPLE_RATES: Record<number, number[]> = {
  3: [44100, 48000, 32000],
  2: [22050, 24000, 16000],
  0: [11025, 12000, 8000],
};

/**
 * Strip the trailing "Generated by FreeTTS" watermark from an MP3 buffer.
 * Returns the trimmed buffer, or null when the input can't be confidently
 * parsed (caller should serve the original audio unchanged).
 */
export function trimFreeTTSWatermark(mp3: Buffer): Buffer | null {
  // Skip a leading ID3v2 tag (10-byte header, syncsafe size) so frame walking
  // starts at real audio.
  let pos = 0;
  if (mp3.length > 10 && mp3.toString("latin1", 0, 3) === "ID3") {
    const size = ((mp3[6] & 0x7f) << 21) | ((mp3[7] & 0x7f) << 14) | ((mp3[8] & 0x7f) << 7) | (mp3[9] & 0x7f);
    pos = 10 + size;
  }

  // Pass 1: walk every frame header, recording [start, length] so the total
  // playtime is known before deciding where to cut. FreeTTS emits MPEG2
  // Layer III @ 24 kHz (576 samples/frame ≈ 24 ms each), but each header is
  // parsed on its own terms so VBR and other rates still work.
  const frames: Array<{ start: number; len: number; seconds: number }> = [];
  let totalSeconds = 0;
  while (pos + 4 <= mp3.length) {
    if (mp3[pos] !== 0xff || (mp3[pos + 1] & 0xe0) !== 0xe0) { pos += 1; continue; } // resync
    const versionBits = (mp3[pos + 1] >> 3) & 0x03;
    const layerBits = (mp3[pos + 1] >> 1) & 0x03;
    if (versionBits === 1 || layerBits !== 1) return null; // not Layer III — unknown encoder; fail-open
    const sampleRate = SAMPLE_RATES[versionBits][(mp3[pos + 2] >> 2) & 0x03];
    if (!sampleRate) return null; // reserved rate index
    const kbps = (versionBits === 3 ? BITRATES_V1_L3 : BITRATES_V2_L3)[(mp3[pos + 2] >> 4) & 0x0f];
    if (!kbps) return null; // reserved/free-form bitrate — frame size unknowable
    const padding = (mp3[pos + 2] >> 1) & 0x01;
    const samplesPerFrame = versionBits === 3 ? 1152 : 576;
    const frameLen = Math.floor((samplesPerFrame === 1152 ? 144 : 72) * kbps * 1000 / sampleRate) + padding;
    if (frameLen < 4 || pos + frameLen > mp3.length) return null; // truncated tail — keep everything
    frames.push({ start: pos, len: frameLen, seconds: samplesPerFrame / sampleRate });
    totalSeconds += samplesPerFrame / sampleRate;
    pos += frameLen;
  }

  if (frames.length < 10 || totalSeconds < MIN_TOTAL_SECONDS) return null;
  const keepUntil = totalSeconds - WATERMARK_CUT_SECONDS;
  if (keepUntil < MIN_KEEP_SECONDS) return null;

  // Pass 2: keep whole frames up to keepUntil; drop the rest (the cut lands in
  // the silence gap between real speech and the watermark — see structure note).
  let acc = 0;
  let endByte = frames[0].start;
  for (const f of frames) {
    if (acc >= keepUntil) break;
    acc += f.seconds;
    endByte = f.start + f.len;
  }
  return mp3.subarray(frames[0].start, endByte);
}
